apiVersion: v1
kind: Service
metadata:
  name: superservice
spec:
  selector: # the selector labels should be of the labels in the pod templates , not others.
    app: expressnode 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
