apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressnode
  labels:
      service: supernode 
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: expressnode
  template:
    metadata:
      labels:
        app: expressnode
    spec:
      containers:
      - name: expressnode
        image: quay.io/narendev/node-graphql
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000